### ISSUE TITLE
Book room @ Mt. Holyoke

### ISSUE THREAD

**Issue by etosch** [CSWomenUMass/tech-skills-workshops#1]

**Comment by strubell** [comment]
https://www.mtholyoke.edu/willits

**Comment by etosch** [comment]
Yup, I believe that's the one. When I called and got the quote, I asked
for a room with a projector and white boards and accommodations for
about 10 people. I didn't ask about catering because I figured there
were affordable restaurants around and it might be good to get out of
the one room. Otoh if it starts early, we might try to get breakfast
catered. It depends on which costs more. I also don't know how strict
they are about us bringing in our own food, eg from Atkins.

## 

  Emma Tosch
  etosch@fastmail.fm

On Mon, Jun 29, 2015, at 08:35 AM, Emma Strubell wrote:

> https://www.mtholyoke.edu/willits
> 
> On Mon, Jun 29, 2015 at 2:22 AM etosch notifications@github.com wrote:
> 
> > Assigned #1
> > https://github.com/CSWomenUMass/tech_skillz_tutorials/issues/1 to
> > @strubell https://github.com/strubell.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/CSWomenUMass/tech_skillz_tutorials/issues/1#event-342625363
> > .
> 
> —
> Reply to this email directly or view it on GitHub[1]. 

Links:
1. https://github.com/CSWomenUMass/tech_skillz_tutorials/issues/1#issuecomment-116735342

**Comment by strubell** [comment]
sweet thanks for the useful info
