### ISSUE TITLE
Book person from CITRL

### ISSUE THREAD

**Issue by etosch** [CSWomenUMass/tech-skills-workshops#2]

**Comment by etosch** [comment]
Any word from Leeanne on whom we should invite? I found this note from the notes on the NCWIT application:

we want something like a bonding session/course development. we expect student teachers to have completed 70-80% of their workshop before the retreat. During the retreat they'll do a practice run, get feedback from peers, discuss things they could do differently, etc. I'd also like to see some bonding between teachers, discussions about pedagogy, and more team-buildling activities. We are asking people to do a lot of work for free, so we want to make sure they're really psyched up for it.

Leeanne suggested we call it "orientation." I called the center for teaching to find out about getting someone out there for half a day to do teacher training for interactive settings. they said they usually don't charge, since it's a service provided by the university.

**Comment by etosch** [comment]
http://www.cirtl.net/

**Comment by strubell** [comment]
I emailed them, waiting to hear back

**Comment by strubell** [comment]
meeting with Beth from CIRTL to discuss on Friday

**Comment by etosch** [comment]
:beer:

## 

  Emma Tosch
  etosch@fastmail.fm

On Mon, Jun 29, 2015, at 10:01 AM, Emma Strubell wrote:

> meeting with Beth from CIRTL to discuss on Friday
> 
> —
> Reply to this email directly or view it on GitHub[1]. 

Links:
1. https://github.com/CSWomenUMass/tech_skillz_tutorials/issues/2#issuecomment-116761808

**Comment by strubell** [comment]
booked Rachel Rybaczuk for 10-11am Monday September 28
